name: Continuous Deployment

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout Master Branch
              uses: actions/checkout@v4

            - name: Setup node 18
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x

            - name: Install Dependencies
              run: npm install

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build
              env:
                  CI: false
                  NODE_ENV: production

            - name: Generate PDF
              run: npm run generate-pdf

            - name: Upload Build Directory
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download Build Directory
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build

            - name: Deploy to Netlify
              uses: netlify/actions/cli@master
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              with:
                  args: deploy --dir=build --prod
